version: '3.9'

volumes:
  mysql:
  redis:


networks:
  reverse-proxy-public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24 # subnet for traefik and other services

services:
  proxy:
    image: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.10 # static IP

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "Asia/Seoul"
    volumes:
      - mysql:/var/lib/mysql
    depends_on:
      - proxy
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.11 # static IP

  cache:
    image: redis
    restart: always
    command:
      [
        "redis-server",
        # Memory management
        "--maxmemory",
        "100mb",
        # LRU eviction policy
        "--maxmemory-policy",
        "allkeys-lru",
        # AOF persistence
        "--appendonly",
        "yes"
          # # RDB persistence
          # "--save",
          # "900 1",
          # "--save",
          # "300 10",
          # "--save",
          # "60 10000",
          # # Disable stop on bgsave error
          # "--stop-writes-on-bgsave-error",
          # "no",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    depends_on:
      - proxy
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.12 # static IP

  api:
    restart: always
    env_file:
      - .env
    build: .
    depends_on:
      - proxy
      - db
      - cache
    labels:
      - "traefik.http.routers.api.rule=HOST(`localhost`, `${HOST_MAIN}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    volumes:
      - .:/app
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.13 # static IP
