version: '3.9'

volumes:
  mysql:
  redis:


networks:
  reverse-proxy-public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24 # subnet for traefik and other services

services:
  proxy:
    image: traefik:latest
    command:
      - "--entrypoints.web.address=:8000"
      - "--providers.docker"
      - "--api.insecure=true"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.10 # static IP

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "Asia/Seoul"
    volumes:
      - mysql:/var/lib/mysql
    depends_on:
      - proxy
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.11 # static IP

  cache:
    image: redis/redis-stack-server:latest
    restart: always
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --maxmemory 100mb --maxmemory-policy allkeys-lru --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    depends_on:
      - proxy
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.12 # static IP
  api:
    image: cosogi/chatgpt-webapp-server-api:latest
    restart: always
    env_file:
      - .env
    # build: .
    depends_on:
      - proxy
      - db
      - cache
    labels:
      - "traefik.http.routers.api.rule=HOST(`localhost`, `${HOST_MAIN}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    volumes:
      - .:/app
    networks:
      reverse-proxy-public:
        ipv4_address: 172.16.0.13 # static IP
